# Configuration for Zendesk KB Translation

# Zendesk Help Center settings
zendesk:
  base_url: "https://support.pendo.io"

# Glossary/Translation Memory
glossary_file: "glossary.yaml"

# Translation settings
translation:
  target_language: "Japanese"
  preserve_html: true
  
# Output settings
output:
  directory: "output"
  format: "markdown"  # Save as markdown files
